/**
 * Property types constants
 * Shared between validation middleware and Mongoose schema
 */

const PROPERTY_TYPES = [
  "apartment",
  "villa",
  //  "house",
  "townhouse",
  "penthouse",
  "studio",
  //  "duplex",
  //  "commercial",
  //  "land",
  "office",
];

const EMIRATES = [
  "Dubai",
  "Abu Dhabi",
  "Sharjah",
  "Ajman",
  "Ras Al Khaimah",
  "Fujairah",
  "Umm Al Quwain",
];

const LISTING_TYPES = ["sale", "rent", "off plan"];

const PROPERTY_STATUS = [
  "available",
  "sold",
  "rented",
  "pending",
  "draft",
  "archived",
];

// Property approval statuses (separate from listing status)
const APPROVAL_STATUS = [
  "pending", // Awaiting SuperAdmin approval
  "approved", // Approved by SuperAdmin - can be published
  "rejected", // Rejected by SuperAdmin - admin can edit/delete
  "not_applicable", // For draft properties - not in approval workflow
];

const AREA_UNITS = ["sqft", "sqm"];

const PARKING_TYPES = ["covered", "open", "garage", "street"];

const PRICE_TYPES = ["total", "per_sqft", "per_sqm"];

const COUNTRIES = ["UAE"];

const CURRENCIES = ["AED"];

// Emirate-Area mapping for validation
const EMIRATE_AREA_MAP = {
  Dubai: [
    "Downtown Dubai",
    "Dubai Marina",
    "Jumeirah Beach Residence (JBR)",
    "Palm Jumeirah",
    "Business Bay",
    "DIFC",
    "Dubai Hills Estate",
    "Arabian Ranches",
    "Jumeirah Village Circle (JVC)",
    "Dubai Sports City",
    "Motor City",
    "The Greens",
    "Emirates Hills",
    "Jumeirah",
    "Bur Dubai",
    "Deira",
    "Al Barsha",
    "Dubai Investment Park (DIP)",
    "International City",
    "Discovery Gardens",
    "Mirdif",
    "Festival City",
    "Silicon Oasis",
    "Dubai South",
    "Al Furjan",
    "Damac Hills",
    "Town Square",
    "Dubai Land",
    "Al Mizhar",
    "Al Warqa",
  ],
  "Abu Dhabi": [
    "Abu Dhabi City",
    "Al Reem Island",
    "Saadiyat Island",
    "Yas Island",
    "Al Reef",
    "Khalifa City",
    "Mohammed Bin Zayed City",
    "Al Shamkha",
    "Al Rahba",
    "Masdar City",
    "Corniche Area",
    "Tourist Club Area",
    "Electra Street",
    "Hamdan Street",
    "Al Bateen",
    "Al Mushrif",
    "Al Karamah",
    "Al Manhal",
    "Al Khalidiyah",
    "Al Markaziyah",
  ],
  Sharjah: [
    "Sharjah City",
    "Al Majaz",
    "Al Qasba",
    "Al Nahda",
    "Muweilah",
    "Al Warqa",
    "University City",
    "Al Taawun",
    "Al Qadisiya",
    "Al Fisht",
  ],
  Ajman: [
    "Ajman City",
    "Al Nuaimiya",
    "Al Rashidiya",
    "Al Jurf",
    "Al Hamidiyah",
  ],
  "Ras Al Khaimah": [
    "RAK City",
    "Al Hamra",
    "Mina Al Arab",
    "Al Marjan Island",
    "Al Rams",
    "Al Jazirah Al Hamra",
  ],
  Fujairah: [
    "Fujairah City",
    "Dibba Al-Fujairah",
    "Kalba",
    "Khor Fakkan",
    "Al Bithnah",
  ],
  "Umm Al Quwain": ["UAQ City", "Al Salamah", "Falaj Al Mualla"],
};

// Property Type - Amenities mapping for dynamic amenities selection
const PROPERTY_TYPE_AMENITIES_MAP = {
  apartment: [
    "Air Conditioning",
    "Central Heating",
    "Built-in Wardrobes",
    "Balcony",
    "City View",
    "Sea View",
    "Marina View",
    "High Floor",
    "Elevator",
    "Swimming Pool",
    "Gym",
    "Security",
    "24/7 Security",
    "CCTV",
    "Concierge",
    "Parking",
    "Covered Parking",
    "Internet Ready",
    "Cable TV Ready",
    "Intercom",
    "Maintenance",
    "Cleaning Service",
    "Pets Allowed",
    "Furnished",
    "Semi Furnished",
    "Unfurnished",
  ],
  villa: [
    "Private Pool",
    "Private Garden",
    "Garage",
    "Maid Room",
    "Driver Room",
    "Study Room",
    "Walk-in Closet",
    "Multiple Living Areas",
    "Formal Dining",
    "Family Room",
    "Home Office",
    "Storage Room",
    "Laundry Room",
    "BBQ Area",
    "Outdoor Kitchen",
    "Jacuzzi",
    "Fireplace",
    "High Ceilings",
    "Marble Floors",
    "Wooden Floors",
    "Smart Home",
    "Solar Panels",
    "Generator Backup",
    "Security System",
    "CCTV",
    "Landscaped Garden",
    "Tree-lined Street",
    "Gated Community",
    "Beach Access",
  ],
  // house: [
  //   "Garden",
  //   "Garage",
  //   "Maid Room",
  //   "Study Room",
  //   "Storage Room",
  //   "Laundry Room",
  //   "Fireplace",
  //   "High Ceilings",
  //   "Wooden Floors",
  //   "Modern Kitchen",
  //   "Built-in Wardrobes",
  //   "Walk-in Closet",
  //   "Multiple Bathrooms",
  //   "Family Room",
  //   "Dining Room",
  //   "Home Office",
  //   "BBQ Area",
  //   "Covered Parking",
  //   "Air Conditioning",
  //   "Central Heating",
  //   "Security System",
  //   "Intercom",
  //   "Internet Ready",
  //   "Furnished",
  //   "Semi Furnished",
  //   "Unfurnished",
  // ],
  townhouse: [
    "Private Garden",
    "Garage",
    "Maid Room",
    "Study Room",
    "Storage Room",
    "Laundry Room",
    "Multiple Levels",
    "Terrace",
    "Rooftop Access",
    "Modern Kitchen",
    "Built-in Wardrobes",
    "Walk-in Closet",
    "Family Room",
    "Dining Room",
    "Home Office",
    "BBQ Area",
    "Covered Parking",
    "Air Conditioning",
    "Central Heating",
    "Community Pool",
    "Community Gym",
    "Playground",
    "Security",
    "Gated Community",
    "Maintenance",
    "Landscaping",
  ],
  penthouse: [
    "Private Pool",
    "Private Terrace",
    "Rooftop Access",
    "Panoramic Views",
    "Sky Lounge",
    "Private Elevator",
    "High-end Finishes",
    "Marble Floors",
    "Floor-to-ceiling Windows",
    "Smart Home System",
    "Home Automation",
    "Premium Kitchen",
    "Wine Cellar",
    "Walk-in Closet",
    "Master Suite",
    "Jacuzzi",
    "Steam Room",
    "Home Theater",
    "Study Room",
    "Maid Room",
    "Driver Room",
    "Laundry Room",
    "Storage Room",
    "Private Garage",
    "Concierge Service",
    "24/7 Security",
    "Valet Parking",
  ],
  studio: [
    "Air Conditioning",
    "Built-in Wardrobes",
    "Balcony",
    "City View",
    "Sea View",
    "High Floor",
    "Modern Kitchen",
    "Marble Floors",
    "Wooden Floors",
    "Swimming Pool",
    "Gym",
    "Security",
    "Elevator",
    "Parking",
    "Covered Parking",
    "Internet Ready",
    "Cable TV Ready",
    "Intercom",
    "Maintenance",
    "Furnished",
    "Semi Furnished",
    "Unfurnished",
    "Compact Design",
    "Efficient Layout",
  ],
  // duplex: [
  //   "Two Levels",
  //   "Private Entrance",
  //   "Terrace",
  //   "Garden",
  //   "Garage",
  //   "Maid Room",
  //   "Study Room",
  //   "Storage Room",
  //   "Laundry Room",
  //   "Multiple Living Areas",
  //   "Formal Dining",
  //   "Modern Kitchen",
  //   "Built-in Wardrobes",
  //   "Walk-in Closet",
  //   "Master Suite",
  //   "Family Room",
  //   "Home Office",
  //   "BBQ Area",
  //   "Air Conditioning",
  //   "Central Heating",
  //   "High Ceilings",
  //   "Wooden Floors",
  //   "Marble Floors",
  //   "Smart Home",
  //   "Security System",
  //   "Covered Parking",
  // ],
  // commercial: [
  //   "Prime Location",
  //   "High Visibility",
  //   "Street Frontage",
  //   "Parking Available",
  //   "Air Conditioning",
  //   "Central Heating",
  //   "Elevator",
  //   "Loading Dock",
  //   "Storage Space",
  //   "Conference Room",
  //   "Reception Area",
  //   "Private Offices",
  //   "Open Plan Layout",
  //   "Kitchen Facilities",
  //   "Bathroom Facilities",
  //   "Security System",
  //   "CCTV",
  //   "Fire Safety System",
  //   "Backup Generator",
  //   "High Speed Internet",
  //   "Phone Lines",
  //   "Disabled Access",
  //   "24/7 Access",
  //   "Maintenance Service",
  //   "Cleaning Service",
  //   "Signage Rights",
  //   "Public Transport Access",
  // ],
  // land: [
  //   "Residential Zoning",
  //   "Commercial Zoning",
  //   "Mixed Use Zoning",
  //   "Corner Plot",
  //   "Main Road Access",
  //   "Utilities Connected",
  //   "Electricity Ready",
  //   "Water Connection",
  //   "Sewage Connection",
  //   "Internet Ready",
  //   "Planning Permission",
  //   "Building Permit Ready",
  //   "Flat Terrain",
  //   "Elevated Position",
  //   "Sea Frontage",
  //   "Beach Access",
  //   "Investment Opportunity",
  //   "Development Potential",
  //   "Gated Community",
  //   "Security",
  //   "Landscaping Allowed",
  //   "No Restrictions",
  //   "Freehold",
  //   "Leasehold",
  // ],
  office: [
    "Prime Location",
    "High Visibility",
    "Street Frontage",
    "Air Conditioning",
    "Central Heating",
    "Elevator",
    "High Speed Elevators",
    "Reception Area",
    "Lobby",
    "Private Offices",
    "Open Plan Layout",
    "Meeting Rooms",
    "Conference Room",
    "Boardroom",
    "Kitchen Facilities",
    "Pantry",
    "Bathroom Facilities",
    "Prayer Room",
    "Storage Space",
    "Server Room",
    "IT Infrastructure",
    "High Speed Internet",
    "Fiber Optic Ready",
    "Phone Lines",
    "Video Conferencing",
    "Security System",
    "24/7 Security",
    "CCTV",
    "Access Control",
    "Fire Safety System",
    "Sprinkler System",
    "Backup Generator",
    "UPS System",
    "Disabled Access",
    "After Hours Access",
    "Maintenance Service",
    "Cleaning Service",
    "Concierge Service",
    "Mail Service",
    "Signage Rights",
    "Building Directory",
    "Public Transport Access",
    "Metro Access",
    "Bus Stop Nearby",
    "Taxi Stand",
    "Restaurant Nearby",
    "Banking Services",
    "Shopping Center Nearby",
    "Hotel Nearby",
    "Furnished",
    "Semi Furnished",
    "Unfurnished",
    "Ready to Move",
    "Shell and Core",
    "Fitted Office",
    "Grade A Building",
    "LEED Certified",
    "Green Building",
    "Sustainable Design",
  ],
};

module.exports = {
  PROPERTY_TYPES,
  EMIRATES,
  LISTING_TYPES,
  PROPERTY_STATUS,
  APPROVAL_STATUS,
  AREA_UNITS,
  PARKING_TYPES,
  PRICE_TYPES,
  COUNTRIES,
  CURRENCIES,
  EMIRATE_AREA_MAP,
  PROPERTY_TYPE_AMENITIES_MAP,
};
